// =============================================================================
// AUTOGENERATED - DO NOT EDIT MANUALLY
// Source: r32i_base_instruction.yaml
// Generated: 2026-03-11T20:45:15
// Instruction Set: RV32I_Base
// =============================================================================
package opcode_defines;

  // ===========================================================================
  // Instruction Format Enum
  // ===========================================================================
  typedef enum logic [2:0] {
    FORMAT_R = 3'd0,  // Register:  funct7 | rs2 | rs1 | funct3 | rd | opcode
    FORMAT_I = 3'd1,  // Immediate: imm[11:0] | rs1 | funct3 | rd | opcode
    FORMAT_S = 3'd2,  // Store:     imm[11:5] | rs2 | rs1 | funct3 | imm[4:0] | opcode
    FORMAT_B = 3'd3,  // Branch:    imm[12|10:5] | rs2 | rs1 | funct3 | imm[4:1|11] | opcode
    FORMAT_U = 3'd4,  // Upper:     imm[31:12] | rd | opcode
    FORMAT_J = 3'd5,  // Jump:      imm[20|10:1|11|19:12] | rd | opcode
    FORMAT_UNKNOWN = 3'd7
  } instr_format_t;

  // ===========================================================================
  // OPCODE Enumerations (sorted by binary value)
  // ===========================================================================
  typedef enum logic [6:0] {
    OPCODE_LOAD   = 7'b0000011,  // LW
    OPCODE_OP_IMM = 7'b0010011,  // ADDI
    OPCODE_STORE  = 7'b0100011,  // SW
    OPCODE_OP     = 7'b0110011,  // ADD, SUB, AND, OR, XOR
    OPCODE_BRANCH = 7'b1100011,  // BEQ, BNE
    OPCODE_JAL    = 7'b1101111   // JAL
  } opcode_t;

  // ===========================================================================
  // FUNCT3 Enumerations
  // ===========================================================================
  typedef enum logic [2:0] {
    FUNCT3_ADDI_ADD = 3'b000,  // ADDI, ADD, SUB, BEQ
    FUNCT3_BNE      = 3'b001,  // BNE
    FUNCT3_LW_SW    = 3'b010,  // LW, SW
    FUNCT3_XOR      = 3'b100,  // XOR
    FUNCT3_OR       = 3'b110,  // OR
    FUNCT3_AND      = 3'b111   // AND
  } funct3_t;

  // ===========================================================================
  // Instruction Properties
  // ===========================================================================

  // LW: rd = M[ rs1 + imm ]
  localparam logic [6:0] LW_OPCODE = 7'b0000011;
  localparam logic [2:0] LW_FUNCT3 = 3'b010;
  localparam instr_format_t LW_FORMAT = FORMAT_I;

  // ADDI: rd = rs1 + imm
  localparam logic [6:0] ADDI_OPCODE = 7'b0010011;
  localparam logic [2:0] ADDI_FUNCT3 = 3'b000;
  localparam instr_format_t ADDI_FORMAT = FORMAT_I;

  // SW: M[ rs1 + imm ] = rs2
  localparam logic [6:0] SW_OPCODE = 7'b0100011;
  localparam logic [2:0] SW_FUNCT3 = 3'b010;
  localparam instr_format_t SW_FORMAT = FORMAT_S;

  // ADD: rd = rs1 + rs2
  localparam logic [6:0] ADD_OPCODE = 7'b0110011;
  localparam logic [2:0] ADD_FUNCT3 = 3'b000;
  localparam logic [6:0] ADD_FUNCT7 = 7'b0000000;
  localparam instr_format_t ADD_FORMAT = FORMAT_R;

  // SUB: rd = rs1 - rs2
  localparam logic [6:0] SUB_OPCODE = 7'b0110011;
  localparam logic [2:0] SUB_FUNCT3 = 3'b000;
  localparam logic [6:0] SUB_FUNCT7 = 7'b0100000;
  localparam instr_format_t SUB_FORMAT = FORMAT_R;

  // AND: rd = rs1 & rs2
  localparam logic [6:0] AND_OPCODE = 7'b0110011;
  localparam logic [2:0] AND_FUNCT3 = 3'b111;
  localparam logic [6:0] AND_FUNCT7 = 7'b0000000;
  localparam instr_format_t AND_FORMAT = FORMAT_R;

  // OR: rd = rs1 | rs2
  localparam logic [6:0] OR_OPCODE = 7'b0110011;
  localparam logic [2:0] OR_FUNCT3 = 3'b110;
  localparam logic [6:0] OR_FUNCT7 = 7'b0000000;
  localparam instr_format_t OR_FORMAT = FORMAT_R;

  // XOR: rd = rs1 ^ rs2
  localparam logic [6:0] XOR_OPCODE = 7'b0110011;
  localparam logic [2:0] XOR_FUNCT3 = 3'b100;
  localparam logic [6:0] XOR_FUNCT7 = 7'b0000000;
  localparam instr_format_t XOR_FORMAT = FORMAT_R;

  // BEQ: if (rs1 == rs2) PC += imm
  localparam logic [6:0] BEQ_OPCODE = 7'b1100011;
  localparam logic [2:0] BEQ_FUNCT3 = 3'b000;
  localparam instr_format_t BEQ_FORMAT = FORMAT_B;

  // BNE: if (rs1 != rs2) PC += imm
  localparam logic [6:0] BNE_OPCODE = 7'b1100011;
  localparam logic [2:0] BNE_FUNCT3 = 3'b001;
  localparam instr_format_t BNE_FORMAT = FORMAT_B;

  // JAL: rd = PC + 4; PC += imm
  localparam logic [6:0] JAL_OPCODE = 7'b1101111;
  localparam instr_format_t JAL_FORMAT = FORMAT_J;

  // ===========================================================================
  // Decode Helper Function
  // ===========================================================================
  function automatic instr_format_t get_format(input opcode_t op);
    case (op)
      OPCODE_LOAD:   return FORMAT_I;
      OPCODE_OP_IMM: return FORMAT_I;
      OPCODE_STORE:  return FORMAT_S;
      OPCODE_OP:     return FORMAT_R;
      OPCODE_BRANCH: return FORMAT_B;
      OPCODE_JAL:    return FORMAT_J;
      default:       return FORMAT_I;
    endcase
  endfunction

endpackage
